# json to coffee compiler
# builds a parser for xml from its inferred structure

file_header = -> "# generated by crampon\n"
file_footer = -> "\nmodule.exports = factory"

header = ->
  """
  class Factory
    build: (tag) ->
      switch tag.tag
  """

footer = ->
  '''
        else throw new Error "unknown tag type #{tag.tag}"

      thing = new Builder()
      tag.getchildren().forEach (child) ->
        thing.set child.tag, child.text, child
      thing

  factory = new Factory()
  '''

class_header = (builder) ->
  """
  class #{builder}
    constructor: ->
  """

set_method_header = ->
  indent = '  '
  """
  #{indent}set: (field, value, tag) ->
  #{indent}  switch field
  """
set_method_footer = (obj) ->
  indent = '      '
  "#{indent}else throw new Error \"unknown field \#{field} on #{obj} object\""

builderize = (tag_name) ->
  singular = tag_name.replace /s$/, ''
  singular[0].toUpperCase() + singular[1..]

make_builder = (name, node) ->
  indent = "      "
  builder = builderize name
  "#{indent}when '#{name}'\n#{indent}  Builder = #{builder}"

builders = (nodes) ->
  (make_builder name, node for name, node of nodes).join '\n'

factory = (inodes, leaves) ->
  """
  #{header()}
  #{builders(inodes)}
  #{footer()}
  """

make_child_map = (child) ->
  "    @#{child} = {}"

make_child_maps = (children) ->
  (make_child_map name for name, plural of children when typeof plural is 'string').join '\n'

make_child_map_setter = (child, name_field) ->
  indent = '      '
  """
  #{indent}when '#{child}'
  #{indent}  thing = factory.build tag
  #{indent}  @#{child}[thing.#{name_field}] = thing
  """

make_child_setters = (children) ->
  setters = []
  for name, plural of children
    if typeof plural is 'string'
      setters.push make_child_map_setter name, plural
    else
      setters.push make_child_simple_setter name, plural
  setters.join '\n'

dictionaries = {}

fieldType = (field) ->
  dictionaries.leaves[field]

make_child_simple_setter = (child) ->
  indent = '      '
  switch fieldType(child)
    when 'number'
      "#{indent}when '#{child}'\n#{indent}  @#{child} = parseInt value, 10"
    when 'boolean'
      "#{indent}when '#{child}'\n#{indent}  @#{child} = value is 'true'"
    else
      "#{indent}when '#{child}'\n#{indent}  @#{child} = value"

named_elements = (name, node) ->
  """
  #{make_child_maps node}
  #{set_method_header()}
  #{make_child_setters node}
  #{set_method_footer name}
  """

make_class = (name, node) ->
  """
  #{class_header builderize name}
  #{named_elements name, node}
  """

classes = (inodes, leaves) ->
  (make_class name, node for name, node of inodes).join '\n\n'

compile = (dicts) ->
  dictionaries = dicts
  """
  #{file_header()}
  #{factory(dicts.inodes, dicts.leaves)}

  #{classes(dicts.inodes, dicts.leaves)}
  #{file_footer()}
  """

module.exports =
  compile: compile
